version: 2

conda:
  environment: docs/environment.yaml

python:
  version: 3.6
  install:
    - method: setuptools # pip
      path: .
      # extra_requirements:
      #     - docs

# default
# sphinx:
#   builder: html
#   configuration: conf.py
#   fail_on_warning: true

