language: python
python:
- "2.7"

cache: pip

services:
- postgresql

addons:
  postgresql: "9.5"

install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- pip install .[precommit,testing]
# the above command does not appear to install pre-commit requirements
- pip install prospector

env:
- TEST_AIIDA_BACKEND=django TEST_TYPE="tests" MOCK_CRY_EXECUTABLES=true
- TEST_AIIDA_BACKEND=sqlalchemy TEST_TYPE="tests" MOCK_CRY_EXECUTABLES=true
- TEST_TYPE="version"
- TEST_TYPE="style"

before_script:
- reentry scan

script:
- if [[ "$TEST_TYPE" == "tests" ]]; then pytest -v; fi
- if [[ "$TEST_TYPE" == "version" ]]; then python .travis-data/check_version.py; fi
- if [[ "$TEST_TYPE" == "style" ]]; then prospector ; fi
#--doctest-modules --ignore=setup.py --ignore=examples

