language: python
python:
- "2.7"

cache: pip

services:
- postgresql

addons:
  postgresql: "9.5"

env:
- TEST_AIIDA_BACKEND=django TEST_TYPE="tests" MOCK_EXECUTABLES=true
- TEST_AIIDA_BACKEND=sqlalchemy TEST_TYPE="tests" MOCK_EXECUTABLES=true
- TEST_TYPE="version"
- TEST_TYPE="style"
- TEST_AIIDA_BACKEND=django TEST_TYPE="tests" MOCK_EXECUTABLES=true AIIDA_BRANCH="develop"

matrix:
  allow_failures:
  - env: TEST_AIIDA_BACKEND=django TEST_TYPE="tests" MOCK_EXECUTABLES=true AIIDA_BRANCH="develop"

install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- >
  if [[ "$AIIDA_BRANCH" == "develop" ]]; then
  cur_path="$(pwd)";
  cd ..;
  git clone --branch=develop https://github.com/aiidateam/aiida_core.git;
  cd aiida_core;
  pip install .[testing];
  cd "$cur_path";
  fi
- pip install .[pre-commit,testing]

before_script:
- reentry scan

script:
- if [[ "$TEST_TYPE" == "tests" ]]; then pytest -v; fi
- if [[ "$TEST_TYPE" == "version" ]]; then python .travis-data/check_version.py; fi
- if [[ "$TEST_TYPE" == "style" ]]; then prospector ; fi
#--doctest-modules --ignore=setup.py --ignore=examples

