language: python
python:
- "2.7"

cache: pip

services:
- postgresql

addons:
  postgresql: "9.5"

env:
  matrix:
    - TEST_TYPE: tests
      TEST_AIIDA_BACKEND: django
      MOCK_EXECUTABLES: true
    - TEST_TYPE: tests
      TEST_AIIDA_BACKEND: sqlalchemy
      MOCK_EXECUTABLES: true
    - TEST_TYPE: version
    - TEST_TYPE: style
    - TEST_TYPE: docs
      READTHEDOCS: 'True'
# TODO for aiida v1 test pytest is failing on setup at present (dependency version clash?)
    - TEST_TYPE: tests
      AIIDA_BRANCH: develop
      TEST_AIIDA_BACKEND: django
      MOCK_EXECUTABLES: true

  allow_failures:
    - TEST_TYPE: tests
      AIIDA_BRANCH: develop
      TEST_AIIDA_BACKEND: django
      MOCK_EXECUTABLES: true

install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- pip install .[pre-commit,testing,docs]
- >
  if [[ ! -z "${AIIDA_BRANCH}" ]]; then
    cur_path="$(pwd)";
    cd ..;
    git clone --branch=${AIIDA_BRANCH} https://github.com/aiidateam/aiida_core.git;
    cd aiida_core;
    pip install -U .[testing];
    cd "$cur_path";
  fi

# TODO limit installation for docs, etc?

before_script:
- reentry scan

script:
- if [[ "$TEST_TYPE" == "tests" ]]; then pytest -v; fi
- if [[ "$TEST_TYPE" == "version" ]]; then python .travis-data/check_version.py; fi
- if [[ "$TEST_TYPE" == "style" ]]; then prospector ; fi
- if [[ "$TEST_TYPE" == "docs" ]]; then cd docs; make; fi
#--doctest-modules --ignore=setup.py --ignore=examples

