language: python
python:
- "2.7"

cache: pip

services:
- postgresql
- rabbitmq  # required for aiida >= 1.0

addons:
  postgresql: "9.5"

env:
  matrix:
    - TEST_TYPE: tests
      TEST_AIIDA_BACKEND: django
      MOCK_EXECUTABLES: true
    - TEST_TYPE: tests
      TEST_AIIDA_BACKEND: sqlalchemy
      MOCK_EXECUTABLES: true
    - TEST_TYPE: pre-commit
    - TEST_TYPE: docs
      READTHEDOCS: 'True'
  # TODO for aiida v1 test pytest is failing on setup at present (dependency version clash?)
    - TEST_TYPE="tests" AIIDA_BRANCH="develop" TEST_AIIDA_BACKEND="django" MOCK_EXECUTABLES=true
    - TEST_TYPE="tests" AIIDA_BRANCH="develop" TEST_AIIDA_BACKEND="sqlalchemy" MOCK_EXECUTABLES=true

matrix:
  allow_failures:
    - env: TEST_TYPE="tests" AIIDA_BRANCH="develop" TEST_AIIDA_BACKEND="django" MOCK_EXECUTABLES=true
    - env: TEST_TYPE="tests" AIIDA_BRANCH="develop" TEST_AIIDA_BACKEND="sqlalchemy" MOCK_EXECUTABLES=true

install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- pip install .[pre-commit,testing,docs]
- >
  if [[ ! -z "${AIIDA_BRANCH}" ]]; then
    cur_path="$(pwd)";
    cd ..;
    git clone --branch=${AIIDA_BRANCH} https://github.com/aiidateam/aiida_core.git;
    cd aiida_core;
    pip install -U .[testing];
    cd "$cur_path";
  fi
- pip install coveralls

before_script:
- reentry scan

script:
- >
  if [[ "$TEST_TYPE" == "tests" ]]; then
    if [[ ! -z "${AIIDA_BRANCH}" ]]; then
      pytest -v;
    else
      pytest -v --cov-config .coveragerc;
    fi
  fi
- >
  if [[ "$TEST_TYPE" == "pre-commit" ]]; then
  pre-commit install;
  pre-commit run --all-files || ( git status --short; git diff ; exit 1 ) ;
  fi
- if [[ "$TEST_TYPE" == "docs" ]]; then cd docs; make; fi

after_success:
- coveralls

deploy:
  distributions: bdist_wheel
  user: cjsewell
  password:
    secure: VCQWK8xNFFKaWOswrtlvEqn/ULz8qjy80Y5xoXjh/tQHnfqtUSHiDh7i5BeDTYepG/C4qkGLApHp2oEOs5JM2bp8QMCVz0ERsMlX8IYAs7iMA85w9rcYWUXk/EkqPC07pyoCLk7wGlSmWnjnrfWfO9Wu5i2Ys7kpiJD6/pcbnGeAuyUv7lI+giAYiDFMjX9T4Iqh2QA2hPjVz0GVqmZyh4FDxlLNJBTvySGlrr4WDjidUamK06eqNBQ6pGGUGRjbu+KNgpSOkZBrLuDJYHhxoqYYPlIGFxWtXyBA1bQxYWWnR0R2iS93TC3TKExznFKsvN/Q11vdlnH6yophJxhimlUhDJXG70cVzsAsxXgLmQtA0Mb5nDsx0lxisAffHeKYAcoSfEg9Fj906L1vH+8/9AnVBQ2sgGB/ob9PpIyvrJoYArMmoj6O/lyNuvzufs6TVUP+iY2+Se8QCwW7l+Izh74GrWBah3Zb4j8JDNLqzjG90qmEoyjMLA67NVDqzfzEIQdZ5q8By5TIJWyv9LhHdJ6Jjl9KQCWD9w9lYzVkYI9W7J7gg8bof9oTLZ9Ntl0NwBpZV3YMpDFQNMl8OP6eNWlXCE5vS2mFPR8Lwk+s1mfq1MrSYXQQKa5m3Dt4p8PzNWrDsf8/94bwR35F+jMfRKdhwRhSvAa8AhXO1y+lJoU=
  on:
    branch: master
    tags: true
    condition: $TEST_AIIDA_BACKEND = "django"
