dist: trusty  # note rabbitmq is currently not available on xenial
language: python

cache: pip

services:
- postgresql
- rabbitmq

addons:
  postgresql: "10.6"
  apt:
    packages:
      - graphviz

matrix:
  include:
    - python: 3.6
      env: TEST_TYPE="pre-commit"
    - python: 3.6
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="django" PYPI_DEPLOY=true
    - python: 2.7
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="django"
    - python: 3.6
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="sqlalchemy"
    - python: 3.6
      env: TEST_TYPE="docs" READTHEDOCS="True"
    - python: 3.6
      env: TEST_TYPE="conda"

  # allow_failures:
  #   - env: TEST_TYPE="docs" READTHEDOCS="True"

install:
# Upgrade pip setuptools and wheel
- pip install --upgrade pip wheel setuptools "reentry>=1.3"
- pip install numpy==1.16.4 # otherwise numpy 1.17 is installed, which is incompatible with aiida-core==1.0.0b5
- |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install typing==3.6.6 # otherwise importlib_resources installs incompatible version for aiida-core==1.0.0b5
    fi
- |
    if [[ "$TEST_TYPE" == "pre-commit" ]]; then
      pip install -e .[code_style]
    fi
- |
    if [[ "$TEST_TYPE" == "pytest" ]]; then
      pip install "notebook<6"  # required by aiida-core->circus->pyzmq<17
      pip install -e .[testing]
      pip install coveralls
    fi
- |
    if [[ "$TEST_TYPE" == "docs" ]]; then
      pip install -e .[docs]
      url="https://github.com/jgm/pandoc/releases/tag/2.6"
      path=$(curl -L $url | grep -o '/jgm/pandoc/releases/download/.*-amd64\.deb')
      downloadUrl="https://github.com$path"
      file=${path##*/}
      wget $downloadUrl && sudo dpkg -i $file
    fi
- |
    if [[ "$TEST_TYPE" == "conda" ]]; then
      # See https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html#the-travis-yml-file
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      hash -r
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      # Useful for debugging any issues with conda
      conda info -a
    fi

# - |
#   if [[ ! -z "${AIIDA_BRANCH}" ]]; then
#     cur_path="$(pwd)"
#     cd ..
#     git clone --branch=${AIIDA_BRANCH} https://github.com/aiidateam/aiida_core.git
#     cd aiida_core
#     pip install -U -e .
#     cd "$cur_path"
#   fi

before_script:
- |
    if [[ "$TEST_TYPE" == "pytest" ]] || [[ "$TEST_TYPE" == "docs" ]]; then
      reentry scan
    fi

script:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      pytest -v --cov=aiida_crystal17 --cov=examples --cov-config .coveragerc --cov-report= aiida_crystal17
  fi
- |
  if [[ "$TEST_TYPE" == "pre-commit" ]]; then
    pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
  fi
- |
  if [[ "$TEST_TYPE" == "docs" ]]; then
    cd docs
    make
  fi
- |
  if [[ "$TEST_TYPE" == "conda" ]]; then
    travis_retry conda env create -f conda_dev_env.yml -n test-environment python=$TRAVIS_PYTHON_VERSION
    conda list -n test-environment
    source activate test-environment
    pip install --no-deps -e .
    reentry scan
    verdi data crystal17.parse --help
  fi

after_success:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      coveralls
  fi

deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: cjsewell
    password:
      secure: VCQWK8xNFFKaWOswrtlvEqn/ULz8qjy80Y5xoXjh/tQHnfqtUSHiDh7i5BeDTYepG/C4qkGLApHp2oEOs5JM2bp8QMCVz0ERsMlX8IYAs7iMA85w9rcYWUXk/EkqPC07pyoCLk7wGlSmWnjnrfWfO9Wu5i2Ys7kpiJD6/pcbnGeAuyUv7lI+giAYiDFMjX9T4Iqh2QA2hPjVz0GVqmZyh4FDxlLNJBTvySGlrr4WDjidUamK06eqNBQ6pGGUGRjbu+KNgpSOkZBrLuDJYHhxoqYYPlIGFxWtXyBA1bQxYWWnR0R2iS93TC3TKExznFKsvN/Q11vdlnH6yophJxhimlUhDJXG70cVzsAsxXgLmQtA0Mb5nDsx0lxisAffHeKYAcoSfEg9Fj906L1vH+8/9AnVBQ2sgGB/ob9PpIyvrJoYArMmoj6O/lyNuvzufs6TVUP+iY2+Se8QCwW7l+Izh74GrWBah3Zb4j8JDNLqzjG90qmEoyjMLA67NVDqzfzEIQdZ5q8By5TIJWyv9LhHdJ6Jjl9KQCWD9w9lYzVkYI9W7J7gg8bof9oTLZ9Ntl0NwBpZV3YMpDFQNMl8OP6eNWlXCE5vS2mFPR8Lwk+s1mfq1MrSYXQQKa5m3Dt4p8PzNWrDsf8/94bwR35F+jMfRKdhwRhSvAa8AhXO1y+lJoU=
    on:
      branch: master
      tags: true
      condition: $PYPI_DEPLOY = true
