language: python

cache: pip

services:
- postgresql
- rabbitmq

addons:
  postgresql: "10.6"
  apt:
    packages:
      - graphviz

matrix:
  include:
    - python: 3.6
      env: TEST_TYPE="code-style"
    - python: 3.6
      env: TEST_TYPE="version"
    - python: 3.6
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="django" MOCK_CRY17_EXECUTABLES=true PYPI_DEPLOY=true
    - python: 2.7
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="django" MOCK_CRY17_EXECUTABLES=true
    - python: 3.6 
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="sqlalchemy" MOCK_CRY17_EXECUTABLES=true
    - python: 3.6
      env: TEST_TYPE="docs" READTHEDOCS="True"

  # allow_failures:
  #   - env: TEST_TYPE="docs" READTHEDOCS="True"

install:
# Upgrade pip setuptools and wheel
- pip install -U "pip<19" wheel setuptools "reentry>=1.3"
- |
    if [[ "$TEST_TYPE" == "version" ]]; then
      pip install click
    fi
- |
    if [[ "$TEST_TYPE" == "code-style" ]]; then
      pip install "flake8<3.8.0,>=3.7.0"
    fi
- |
    if [[ "$TEST_TYPE" == "pytest" ]]; then
      pip uninstall -y numpy
      pip install -e .[testing]
      pip install coveralls
    fi
- |
    if [[ "$TEST_TYPE" == "docs" ]]; then
      pip uninstall -y numpy
      pip install -e .[docs]
      url="https://github.com/jgm/pandoc/releases/tag/2.6"
      path=$(curl -L $url | grep -o '/jgm/pandoc/releases/download/.*-amd64\.deb')
      downloadUrl="https://github.com$path"
      file=${path##*/}
      wget $downloadUrl && sudo dpkg -i $file
    fi
# - |
#   if [[ ! -z "${AIIDA_BRANCH}" ]]; then
#     cur_path="$(pwd)"
#     cd ..
#     git clone --branch=${AIIDA_BRANCH} https://github.com/aiidateam/aiida_core.git
#     cd aiida_core
#     pip install -U -e .
#     cd "$cur_path"
#   fi

before_script:
- |
    if [[ "$TEST_TYPE" == "pytest" ]] || [[ "$TEST_TYPE" == "docs" ]]; then
      reentry scan
    fi

script:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      pytest -v --cov=aiida_crystal17 --cov=examples --cov-config .coveragerc --cov-report= aiida_crystal17
  fi
- |
  if [[ "$TEST_TYPE" == "code-style" ]]; then
    flake8 .
  fi
- |
  if [[ "$TEST_TYPE" == "docs" ]]; then
    cd docs
    make
  fi
- |
  if [[ "$TEST_TYPE" == "version" ]]; then
    python ./.travis-data/check_version.py version
  fi

after_success:
- coveralls

deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: cjsewell
    password:
      secure: VCQWK8xNFFKaWOswrtlvEqn/ULz8qjy80Y5xoXjh/tQHnfqtUSHiDh7i5BeDTYepG/C4qkGLApHp2oEOs5JM2bp8QMCVz0ERsMlX8IYAs7iMA85w9rcYWUXk/EkqPC07pyoCLk7wGlSmWnjnrfWfO9Wu5i2Ys7kpiJD6/pcbnGeAuyUv7lI+giAYiDFMjX9T4Iqh2QA2hPjVz0GVqmZyh4FDxlLNJBTvySGlrr4WDjidUamK06eqNBQ6pGGUGRjbu+KNgpSOkZBrLuDJYHhxoqYYPlIGFxWtXyBA1bQxYWWnR0R2iS93TC3TKExznFKsvN/Q11vdlnH6yophJxhimlUhDJXG70cVzsAsxXgLmQtA0Mb5nDsx0lxisAffHeKYAcoSfEg9Fj906L1vH+8/9AnVBQ2sgGB/ob9PpIyvrJoYArMmoj6O/lyNuvzufs6TVUP+iY2+Se8QCwW7l+Izh74GrWBah3Zb4j8JDNLqzjG90qmEoyjMLA67NVDqzfzEIQdZ5q8By5TIJWyv9LhHdJ6Jjl9KQCWD9w9lYzVkYI9W7J7gg8bof9oTLZ9Ntl0NwBpZV3YMpDFQNMl8OP6eNWlXCE5vS2mFPR8Lwk+s1mfq1MrSYXQQKa5m3Dt4p8PzNWrDsf8/94bwR35F+jMfRKdhwRhSvAa8AhXO1y+lJoU=
    on:
      branch: master
      tags: true
      condition: $PYPI_DEPLOY = true
