language: python
python:
- "2.7"

cache: pip

services:
- postgresql

addons:
  postgresql: "9.5"

install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- pip install .[precommit,testing]

env:
- TEST_TYPE="pre-commit"
- TEST_AIIDA_BACKEND=django TEST_TYPE="tests"
- TEST_AIIDA_BACKEND=sqlalchemy TEST_TYPE="tests"

before_script:
- reentry scan

script:
- if [[ "$TEST_TYPE" == "pre-commit" ]]; pre-commit run --all-files || ( git status --short ; git diff ; exit 1 ); fi
- if [[ "$TEST_TYPE" == "pre-commit" ]]; python .travis-data/check_version.py; fi
- if [[ "$TEST_TYPE" == "tests" ]]; pytest -v; fi
#--doctest-modules --ignore=setup.py --ignore=examples

