conda_env: aiida_workshop
aiida_version: 1.0.0b1
aiida_path: /Users/cjs14/GitHub/aiida-crystal17/databases/aiida/
db_pgsql:
  path: /Users/cjs14/GitHub/aiida-crystal17/databases/pgsql/test_v1_1
  user: cjs14
  user-password: niceday  # should handle this more securely
  name: test_v1_1
  port: 5432  
db_aiida:
  path: /Users/cjs14/GitHub/aiida-crystal17/databases/aiida/test_v1_1
  profile: test_v1_1
  email: chrisj_sewell@hotmail.com
  first-name: Chris
  last-name: Sewell
  institution: Imperial College London