name: aiida_1a4
channels:
- conda-forge
- matsci  # for pymatgen
- cjs14 # currently for pg8000, pgtest, sqlalchemy-diff, sphinxcontrib-contentui
- anaconda # for sphinx_rtd_theme 
- defaults
dependencies:
  - python==3.6
  - pip=18.1  # CJS pip==19.0.3 breaks pip install of aiida_core, see https://github.com/pypa/pip/issues/6163
  # non-python requirement
  - rabbitmq-server
  - postgresql>=9.4
  # from install_requires
  - reentry==1.2.2  # CJS this was 1.2.1 but thats not availble in conda-forge
  - python-dateutil==2.7.2
  - python-mimeparse==1.6.0
  - django==1.8.19
  - django-extensions==1.7.7  
  # CJS ==1.5.0 UnsatisfiableError: django-extensions==1.5.0 -> django[version='<=1.8'] -> python[version='>=2.7,<2.8.0a0']
  # the earliest to have a 3.6 dist is 1.7.7
  - tzlocal==1.5.1
  - pytz==2018.4
  - PyYAML==3.12
  - six==1.11.0
  - anyjson==0.3.3
  - psutil==5.4.5
  - meld3==1.0.2
  - mock==2.0.0
  - numpy==1.14.3
  - SQLAlchemy==1.2.12
  - SQLAlchemy-Utils==0.33.0
  - alembic==0.9.9
  - ujson==1.35
  - aldjemy==0.8.0
  - passlib==1.7.1
  - validate_email==1.3  # CJS this was named validate-email, but I'm guessing their the same?
  - click==6.7
  - click-completion==0.3.1
  - click-plugins==1.0.3
  - click-spinner==0.1.7
  - tabulate==0.8.2
  - ete3==3.1.1
  - uritools==2.1.0
  - psycopg2==2.7.5  # CJS ==2.7.6 UnsatisfiableError: psycopg2==2.7.6 -> python[version='>=3.7,<3.8.0a0']
  - paramiko==2.4.2
  - ecdsa==0.13
  - ipython>=4.0,<6.0  # Version of ipython non enforced, because some still prefer version 4 rather than the latest
  - plumpy==0.11.5  # CJS this was 0.11.4 but that's not availble in conda-forge
  - circus==0.14.0  
  - tornado==4.5.3  # As of 2018/03/06 Tornado released v5.0 which breaks circus 0.14.0
  # - pyblake2==1.1.2; python_version<"3.6"
  # - chainmap; python_version<"3.5"
  # - pathlib2; python_version<"3.5"
  # - singledispatch>=3.4.0.3; python_version<"3.5"
  # - enum34==1.1.6; python_version<"3.5"
  - simplejson==3.16.0
  
  # from testing
  # - unittest2==1.1.0; python_version<"3.5"
  - pgtest==1.1.0
  - sqlalchemy-diff==0.1.3
  # - coverage==4.5.1
  # - codecov==2.0.15
  # - futures; python_version=="2.7"

  # from docs
  - sphinx==1.8.4
  - pygments==2.3.1
  - docutils==0.14
  - jinja2==2.10
  - markupsafe==1.1.1
  - sphinx-rtd-theme==0.4.2 # CJS ==0.4.3 not avaliable on conda
  - sphinxcontrib-contentui==0.2.2
  
  # from atomic_tools
  - spglib==1.10.3.65
  - pymatgen==2018.4.20
  - ase==3.12.0  # Updating breaks tests

  # for aiiida-crystal17
  - jsonextended
  - ejplugins
  - pytest==3.6.3
  - pytest-timeout

  # for vs code development
  - flake8
  - autopep8

  # - pip:
  #   - .

# RUN
# >> conda clean all
# >> conda env create --file=conda_env_py36_aiida1a4.yaml
# >> conda activate aiida_1a4
# >> pip install --no-deps -e path/to/aiida_core
# >> pip install --no-deps -e path/to/aiida-crystal17
# would be nice to add this to pip section (above), 
# but looks like you can't set package specific options https://github.com/conda/conda/issues/6805

# TESTS
# >> rabbitmq-server -detached
# to run test with mock crystal17 executable
# >> export MOCK_EXECUTABLES=true
# >> pytest
# or for short tracebacks, etc
# pytest -v --no-print-logs --show-capture=no --tb=short

# NOTE:
# in conda create,
# I get a lot of: ClobberError: This transaction has incompatible packages due to a shared path.
# for tk/xorg and libpq/postgresql
# possibly relate issue: https://github.com/conda/conda/issues/7038
# this doesn't seem to affect the actual build