name: aiida_1b1
channels:
- conda-forge
- matsci  # for pymatgen
- cjs14 # currently for pg8000, pgtest, sqlalchemy-diff
- anaconda # for sphinx_rtd_theme 
- defaults
dependencies:
  # build dependencies
  - python==3.6
  - pip=18.1  # CJS pip==19.0.3 breaks pip install of aiida_core, see https://github.com/pypa/pip/issues/6163
  # non-python dependencies
  - rabbitmq-server
  - postgresql>=9.4
  # from install_requires
  - reentry==1.2.2
  - python-dateutil==2.8.0
  - python-mimeparse==1.6.0
  - django==1.11.16  # CJS ==1.11.20 not on conda-forge
  - tzlocal==1.5.1
  - pytz==2018.9
  - PyYAML==3.13
  - six==1.12.0
  - anyjson==0.3.3
  - psutil==5.5.1
  - meld3==1.0.2
  - mock==2.0.0
  - numpy==1.16.1
  - SQLAlchemy==1.2.18
  - SQLAlchemy-Utils==0.33.11
  - alembic==1.0.7
  - ujson==1.35
  - aldjemy==0.9.1
  - passlib==1.7.1
  - click==7.0
  - click-completion==0.5.0
  - click-plugins==1.0.4
  - click-spinner==0.1.8
  - tabulate==0.8.3
  - ete3==3.1.1
  - uritools==2.2.0
  - psycopg2==2.7.5  # CJS ==2.7.6 UnsatisfiableError: psycopg2==2.7.6 -> python[version='>=3.7,<3.8.0a0']
  - paramiko==2.4.2
  - ecdsa==0.13
  - ipython>=4.0,<6.0  # Version of ipython non enforced, because some still prefer version 4 rather than the latest
  - plumpy==0.12.1
  - kiwipy==0.3.10  # CJS in setup.json has extras kiwipy[rmq]==0.4.2, plump requires <4.0
  - pika==1.0.0b1
  - circus==0.14.0  # CJS ==0.15.0 not on conda-forge
  - tornado<5.0  # As of 2018/03/06 Tornado released v5.0 which breaks circus 0.14.0
  # - pyblake2==1.1.2; python_version<"3.6"
  # - chainmap; python_version<"3.5"
  # - pathlib2; python_version<"3.5"
  # - singledispatch>=3.4.0.3; python_version<"3.5"
  # - enum34==1.1.6; python_version<"3.5"
  - simplejson==3.16.0
  # - typing==3.6.6; python_version<'3.5'"
  
  # from testing
  # - unittest2==1.1.0; python_version<"3.5"
  - pgtest==1.1.0
  - pg8000<1.13.0
  - sqlalchemy-diff==0.1.3
  # - coverage==4.5.2
  # - codecov==2.0.15
  # - futures; python_version=="2.7"
  # - pytest==4.3.0
  # - pytest-cov==2.6.1

  # from docs
  - sphinx==1.8.4
  - pygments==2.3.1
  - docutils==0.14
  - jinja2==2.10
  - markupsafe==1.1.1
  - sphinx_rtd_theme==0.4.2 # CJS ==0.4.3 not avaliable on conda
  - sphinxcontrib-contentui==0.2.2

  # from rest
  - Flask==1.0.2
  - Flask-RESTful==0.3.6  # CJS ==0.3.7 not on conda-forge
  - Flask-Cors==3.0.7
  - Flask-HTTPAuth==3.2.4
  - Flask-Cache==0.13.1
  - Flask-SQLAlchemy==2.3.2
  - flask-marshmallow==0.9.0
  - pyparsing==2.3.1
  - sqlalchemy-migrate==0.11.0  # CJS ==0.12.0 not on conda-forge
  - marshmallow-sqlalchemy==0.16.0
  - itsdangerous==1.1.0
  - python-memcached==1.59
  
  # from atomic_tools
  - spglib==1.12.2 # CJS 1.12.2.post0 not on conda-forge
  - pymatgen<=2018.12.12
  - ase==3.17.0

  # for aiiida-crystal17
  - jsonextended
  - ejplugins
  - pytest==3.6.3
  - pytest-timeout
  - packaging

  # for vs code development
  - flake8
  - autopep8
  - rope

  # - pip:
  #   - .

# INSTALL aiida
# >> conda clean all
# >> conda env create --file=conda_env_py36_aiida1b1.yaml
# >> conda activate aiida_1b1
# >> cd path/to/aiida_core_develop
# >> pip install --no-deps -e .
# >> cd path/to/aiida-crystal17
# >> pip install --no-deps -e .
# would be nice to add this to pip section (above), 
# but looks like you can't set package specific options https://github.com/conda/conda/issues/6805

# verdi tab completion 
# >> eval "$(_VERDI_COMPLETE=source verdi)"

# aiida-crystal17 TESTS
# >> rabbitmq-server -detached
# to run test with mock crystal17 executable
# >> export MOCK_EXECUTABLES=true
# >> pytest
# or for short tracebacks, etc
# pytest -v --no-print-logs --show-capture=no --tb=short

# BUILD DOCS
# >> rabbitmq-server -detached
# >> initdb -D /Users/cjs14/pgsql/data1b
# >> pg_ctl -D /Users/cjs14/pgsql/data1b -l logfile start
# >> verdi quicksetup
# >> cd path/to/aiida_core_develop/docs
# >> make
