# Usage: conda env create -n myenvname -f conda_dev_env.yml python=3.6
#        conda activate myenvname
#        pip install --no-deps -e .
name: aiida_crystal17
channels:
- conda-forge
- cjs14  # for sqlalchemy-diff and pgtest
dependencies:
- pip
- aiida-core.services
# install_requires
- aiida-core>=1.4.0,<2.0.0
- ase>=3.12.0,<4.0.0
- importlib_resources
- jsonextended>=0.7.10
- jsonschema
- pycifrw>=4.4.1,<5.0.0
- pyyaml
- spglib>=1.10.0,<2.0.0
# testing
- coverage
- pgtest
- pytest
- pytest-cov
- pytest-notebook
- pytest-regressions
- pytest-timeout
# code_style
- pre_commit~=2.6
# docs
- myst-nb~=0.10.1
- sphinx-book-theme
