# Usage: conda env create -n myenvname -f conda_dev_env.yml python=3.6
name: aiida_crystal17
channels:
- conda-forge
- cjs  # for sqlalchemy-diff and pgtest
dependencies:
- aiida-core.services
# install_requires
- aiida-core==1.0.0b5
- ase>=3.12.0,<4.0.0
- jsonextended>=0.7.10
- jsonschema
- pycifrw==4.4
- ruamel.yaml
- six
- spglib>=1.10.0,<2.0.0
# testing
- coverage
- mock==2.0.0
- pgtest==1.2.0
- pytest-cov
- pytest-regressions
- pytest-timeout
- pytest==3.6.3
- sqlalchemy-diff==0.1.3
- wheel>=0.31
# code_style
- flake8<3.8.0,>=3.7.0
- pre-commit==1.14.4
- yapf==0.26.0
# docs
- ipypublish>=0.10.7
- sphinx>=1.6
