channels:
  - conda-forge
dependencies:
  - python =3.6
  - pandoc =2.6
  - docutils >=0.15
  - python-graphviz
  - ipypublish >=0.10.7
  - pyyaml ==3.13  # required for aiida-core, and can't be uninstalled by pip
