channels:
  - conda-forge
dependencies:
  - python =3.6
  # - pandoc
  - python-graphviz
  - ipypublish >=0.10
  # - reentry >=1.3
  # - setuptools
  # - wheel
  - pip =18
  # - pip:
  #   - reentry>=1.3
  #   - aiida-core==1.0.0b2
