channels:
  - conda-forge
dependencies:
  - python =3.6
  - pandoc
  - python-graphviz
  - ipypublish >=0.10.1
  - pyyaml ==3.13  # required for aiida-core, and can't be uninstalled by pip
  # - pip <19
